# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- script: |
    echo THIS IS ONE BIG TEST echo See https://aka.ms/yaml
  displayName: 'Some other script that I want to run script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'DevSubscription(0abb6ec5-9030-4b3f-af04-09183c688576)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './build_and_delete.sh'